shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: nexus
      password: nexus
      dbname: analytics
      schema: public
      threads: 4
